In [17]:
# This problem was asked by Uber.
# Given an array of integers, return a new array such that each
# element at index i of the new array is the product of all 
# the numbers in the original array except the one at i.
# For example, if our input was [1, 2, 3, 4, 5], the expected
# output would be [120, 60, 40, 30, 24]. If our input was [3, 2, 1]
# the expected output would be [2, 3, 6].


import numpy as np

mylist = [1, 2, 3, 4, 5]
mylist1 = [3, 2, 1]

def myfunc(mylist):
    forw = np.ones(len(mylist))
    backw = np.ones(len(mylist))
    out = np.ones(len(mylist))
    it = 0
    jt = len(mylist) - 1
    kt = 0
    
    for item in mylist:
        if it == 0:
            forw[0] = mylist[0]
        else :
            forw[it] = forw[it-1]*mylist[it]
        it = it + 1   
            
    for item in mylist:
        if jt == len(mylist) - 1:
            backw[jt] = mylist[jt]
        else:
            backw[jt] = backw[jt+1]*mylist[jt]
        jt = jt -1
        
    for item in mylist:
        left = kt - 1
        right = kt + 1
        if left >= 0 and left < len(mylist):
            out[kt] = out[kt]*forw[left]
        if right >= 0 and right < len(mylist):
            out[kt] = out[kt]*backw[right]
        kt=kt+1
        
    return (forw, backw, out)
        

In [18]:
myfunc(mylist)

(array([  1.,   2.,   6.,  24., 120.]),
 array([120., 120.,  60.,  20.,   5.]),
 array([120.,  60.,  40.,  30.,  24.]))

In [19]:
myfunc(mylist1)

(array([3., 6., 6.]), array([6., 2., 1.]), array([2., 3., 6.]))

In [32]:
def myfunc1(mylist):
    zeroset = []
    product = 1
    out = np.ones(len(mylist))
    it = 0
    for item in mylist:
        if item > 0:
            product = product * item
        if item == 0:
            zeroset.append(it)
        it = it + 1
    if len(zeroset) > 1:
        out = np.zeros(len(mylist))
    elif len(zeroset) == 1:
        out = np.zeros(len(mylist))
        out[zeroset[0]] = product
    elif len(zeroset) == 0:
        it = 0
        for item in mylist:
            out[it] = product/item
        
    return out
        

In [21]:
mylist2 = [4, 5, 0, 6, 7]

In [22]:
myfunc(mylist2)

(array([ 4., 20.,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., 42.,  7.]),
 array([  0.,   0., 840.,   0.,   0.]))

In [33]:
myfunc1(mylist2)

array([  0.,   0., 840.,   0.,   0.])